import {Audio, interpolate, Sequence, staticFile} from 'remotion';
import {SCENE_CLICKS} from './scenes/Features';
import {AGENT_CHAT} from './scenes/AgentChat';
import {SCENE_START, SceneName, TOTAL_FRAMES} from './timing';

const Sfx: React.FC<{src: string; at: number; volume?: number; duration?: number}> = ({src, at, volume = 1, duration}) => (
  <Sequence from={Math.max(0, Math.round(at))} durationInFrames={duration} layout="none">
    <Audio src={staticFile(`audio/${src}`)} volume={volume} />
  </Sequence>
);

// Music bed (120 BPM = one beat every 15 frames) plus sound effects synced to the animation.
// Audio files are generated by scripts/generate_audio.py.
export const Soundtrack: React.FC = () => {
  const scenes = Object.keys(SCENE_START) as SceneName[];
  const chat = SCENE_START.agentChat;
  const A = AGENT_CHAT;
  return (
    <>
      <Audio
        src={staticFile('audio/music.wav')}
        volume={(f) => interpolate(f, [0, 10, TOTAL_FRAMES - 20, TOTAL_FRAMES], [0, 0.6, 0.6, 0], {extrapolateRight: 'clamp'})}
      />
      <Sfx src="riser.wav" at={0} volume={0.45} />
      <Sfx src="impact.wav" at={38} volume={0.6} />
      {scenes.slice(1).map((s) => (
        <Sfx key={s} src="whoosh.wav" at={SCENE_START[s]} volume={0.35} />
      ))}
      {scenes.flatMap((s) =>
        (SCENE_CLICKS[s] ?? []).map((c) => <Sfx key={`${s}-${c}`} src="click.wav" at={SCENE_START[s] + c} volume={0.7} />),
      )}
      <Sfx src="typing.wav" at={chat + A.type1[0]} duration={A.type1[1] - A.type1[0]} volume={0.35} />
      <Sfx src="typing.wav" at={chat + A.type2[0]} duration={A.type2[1] - A.type2[0]} volume={0.35} />
      <Sfx src="pop.wav" at={chat + A.send1} volume={0.5} />
      <Sfx src="pop.wav" at={chat + A.send2} volume={0.5} />
      <Sfx src="ding.wav" at={chat + A.answer1} volume={0.35} />
      <Sfx src="ding.wav" at={chat + A.answer2} volume={0.35} />
      <Sfx src="impact.wav" at={TOTAL_FRAMES - 90} volume={0.5} />
    </>
  );
};
